import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import Home from "@/components/Home"
import SkillsSection from "@/components/Skill";
import AboutPage from "./aboutPage/AboutPage";
import ProcessPage from "./workProcess/WorkProcess";
import ContactSection from "./contactPage/ContactPage";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar></Navbar>
        <Banner></Banner> */}
        <Home></Home>
        <SkillsSection></SkillsSection>
        <AboutPage></AboutPage>
        <ProcessPage></ProcessPage>
        <ContactSection></ContactSection>
        <Footer></Footer>
        {children}
      </body>
    </html>
  );
}
